--- #YAML:1.0
name:                Array-Rotatable
version:             0.001
abstract:            Rotatable Array Object
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ryo Okamoto <ryo@apple.com>
